language: generic
sudo: false

branches:
  only:
    - stable
    - master

matrix:
  include:
  - os: linux
    language: generic
    dist: trusty
  - os: linux
    language: generic
    dist: precice
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic

install:
  - make clean || true
  - make install 2>/dev/null || true

script:
  - make clean || true
  - make test

after_success:
  - echo "Done."

