language: generic
sudo: false

dist:

env:

branches:
  only:
    - stable
    - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

matrix:
  include:
  - os: linux
    sudo: true
    addons:
      apt:
        packages:
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev
          - cmake
    language: generic
    dist: trusty
  - os: linux
    sudo: false
    language: generic
    dist: trusty
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
 allowed failures:
  - os: linux
    sudo: true
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: linux
    language: generic
    dist: precice

before_install:
  - travis_retry gem install bashcov || true

install:
  - make clean || true
  - make install 2>/dev/null || true

before_script:
  - make clean || true

script:
  - bashcov -- make test || make test

after_script:
  - ls -lap || true

after_success:
  - ./tests/travis_prep_kcov.sh || true
  - echo "Done."

