language: generic
sudo: false

branches:
  only:
    - stable
    - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

dist:

Env:

matrix:
  include:
  - os: linux
    sudo: true
    addons:
      apt:
        packages:
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev
          - cmake
    language: generic
    dist: trusty
  - os: linux
    sudo: false
    language: generic
    dist: trusty
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  - os: osx
    osx_image: xcode9.2
    language: generic
  - os: osx
    osx_image: xcode9.3
    language: generic
  - os: osx
    osx_image: xcode9.4
    language: generic
  - os: osx
    osx_image: xcode10
    language: generic
  allow_failures:
  - os: linux
    python:  "nightly" # currently points to 3.7-dev
    env: TRAVIS_PYTHON_VERSION="3.7-dev"
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9.2
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  - os: linux
    sudo: true
  - os: linux
    language: generic
    dist: precice

before_install:
  - travis_retry gem install bashcov || true

install:
  - make clean || true
  - make install 2>/dev/null || true

script:
  - make clean || true
  - which -a make
  - bashcov -- ./tests/bashcov_run.sh || make test
  - ls -lap coverage || true

after_success:
  - ./tests/travis_prep_kcov.sh || true
  - make clean || true
  - echo "Done."

after_failure:
  - make clean || true
  - echo "Done."

